GET http://localhost:8080/board/list


###
POST http://localhost:8080/api/account/logout
Accept: application/json
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmNkMTIzQGFiY2QuY29tIiwiZXhwIjoxNjY2MDI4NTI5LCJpYXQiOjE2NjYwMTg1Mjl9.6tjILCqea6Dx_hqHbF00RIMACvLiHDmtmwKp48XpjK0


###

GET http://localhost:8080/api/account/renew
Accept: application/json
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmNkMTIzQGFiY2QuY29tIiwiZXhwIjoxNjY2MDI4NTI5LCJpYXQiOjE2NjYwMTg1Mjl9.6tjILCqea6Dx_hqHbF00RIMACvLiHDmtmwKp48XpjK0


###

POST http://localhost:8080/api/account/login
Content-Type: application/json

{
  "email": "abcd123@abcd.com",
  "password": "dcba1234!"
}

###

POST http://localhost:8080/api/account/signup
Content-Type: application/json

{
  "email": "abcd123@abcd.com",
  "nickname" : "abcdman",
  "password": "dcba1234!",
  "checkPassword": "dcba1234!"
}
###





