POST http://localhost:8080/api/account/logout
Accept: application/json
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmNkMTIzQGFiY2QuY29tIiwiZXhwIjoxNjY2MDI2NDIxLCJpYXQiOjE2NjYwMTY0MjF9.7MpQveSm-tkDFEO6_SFNQ7e8AVUkNjueRMdY_cu1xQY


###

GET http://localhost:8080/api/account/renew
Accept: application/json
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmNkMTIzQGFiY2QuY29tIiwiZXhwIjoxNjY2MDI1MTM5LCJpYXQiOjE2NjYwMTUxMzl9.tel3DQ2JtY3Dc5_a3Vd_WShSBTypNvEAYGl16CSrSys


###

POST http://localhost:8080/api/account/login
Content-Type: application/json

{
  "email": "abcd123@abcd.com",
  "password": "dcba1234!"
}

###

POST http://localhost:8080/api/account/signup
Content-Type: application/json

{
  "email": "abcd123@abcd.com",
  "nickname" : "abcdman",
  "password": "dcba1234!",
  "checkPassword": "dcba1234!"
}
###





